pie(table(iris$Species))
hist(iris$Sepal.Length)
plot(density(iris$Sepal.Length))
plot(iris$Sepal.Length, iris$Sepal.Width)
plot(iris)
x<-iris
barplot(quantile(iris$Sepal.Length))
install.packages("scatterplot3d")
library(scatterplot3d)
scatterplot3d(iris$Petal.Width, iris$Sepal.Length, iris$Sepal.Width)
library(rgl)
plot3d(iris$Petal.Width, iris$Sepal.Length, iris$Sepal.Width)
distMatrix <- as.matrix(dist(iris[,1:4]))
heatmap(distMatrix)
library(lattice)
levelplot(Petal.Width~Sepal.Length*Sepal.Width, iris, cuts=9,col.regions=grey.colors(10)[10:1])
filled.contour(volcano, color=terrain.colors, asp=1,plot.axes=contour(volcano, add=T))
persp(volcano, theta=25, phi=30, expand=0.5, col="lightblue")
library(MASS)               
parcoord(iris[1:4], col=iris$Species)
parallelplot(~iris[1:4] | Species, data=iris)
library(ggplot2)
qplot(Sepal.Length, Sepal.Width, data=iris, facets=Species ~.)
